name: WyRM
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2020.6.20
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - jsonpickle=2.0.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.10.0
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - asttokens==2.0.5
    - dice==3.1.2
    - docopt==0.6.2
    - executing==0.8.2
    - pure-eval==0.2.2
    - pyparsing==3.0.7
    - six==1.16.0
    - varname==0.8.1
