name: WyRM
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - certifi=2020.6.20
  - decorator=5.1.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - ipython=8.1.1
  - jedi=0.18.1
  - js2py=0.71
  - jsonpickle=2.0.0
  - lark=1.1.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - matplotlib-inline=0.1.2
  - ncurses=6.3
  - openssl=1.1.1m
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyjsparser=2.7.1
  - python=3.10.0
  - python-tzdata=2021.5
  - python_abi=3.10
  - pytz-deprecation-shim=0.1.0.post0
  - readline=8.1.2
  - regex=2021.8.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - stack_data=0.2.0
  - tk=8.6.11
  - traitlets=5.1.1
  - tzdata=2021e
  - tzlocal=4.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - attrs==21.4.0
    - dice==3.1.2
    - docopt==0.6.2
    - executing==0.8.2
    - linkify-it-py==1.0.3
    - markdown-it-py==2.0.1
    - mdformat==0.7.14
    - mdformat-footnote==0.1.1
    - mdformat-frontmatter==0.4.1
    - mdformat-gfm==0.3.5
    - mdformat-tables==0.4.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.0
    - pyparsing==3.0.7
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.1
    - qscintilla==2.10.8
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - tomli==2.0.1
    - uc-micro-py==1.0.1
    - varname==0.8.1
